baseURL = "https://pubxel.org/"
languageCode = "en-us"
title = "Pub-Xel"
theme = "digitalgarden2"

googleAnalytics = "G-QCHBQTC6WG"


[Params]
  title = "Pub-Xel"
  description = "A Biomedical Reference Management Tool"
  images = ['/pubxel-logo.png']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'News'
  url = '/articles'
  weight = 2

[[menu.main]]
  name = 'Resources'
  url = '/resources'
  weight = 3

[[menu.main]]
  name = 'Team'
  url = '/author'
  weight = 4

[[menu.main]]
  name = 'Pub-Xel OncoTwitter'
  params.header = true
  weight = 11

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 12

[[menu.main]]
  name = 'Pub-Xel App'
  params.header = true
  weight = 21

[[menu.main]]
  name = 'Introduction'
  url = '/introduction'
  weight = 22

[[menu.main]]
  name = 'Download'
  url = '/download/latest'
  weight = 23

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/crossing96/Pub-Xel'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:info@pubxel.org'
  weight = 8

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

[privacy.x]
simple = false

[services.x]
disableInlineCSS = true